BUG: check LD_LIBRARY_PATH when looking libpython.so on installation

diff --git a/SuperBuild/Packaging/Files/linux_pkgsetup.in b/SuperBuild/Packaging/Files/linux_pkgsetup.in
--- a/SuperBuild/Packaging/Files/linux_pkgsetup.in
+++ b/SuperBuild/Packaging/Files/linux_pkgsetup.in
@@ -11,7 +11,11 @@ OUT_DIR=$(pwd)
 PATCH_ELF_EXE="$OUT_DIR/patchelf"
 
 # No no interference with LD_LIBRARY_PATH
-LD_LIBRARY_PATH=
+LD_LIBRARY_PATH_COPY="";
+if [ -z "$LD_LIBRARY_PATH" ] || [ "$LD_LIBRARY_PATH" = "" ]; then
+    LD_LIBRARY_PATH_COPY=$LD_LIBRARY_PATH
+fi
+unset LD_LIBRARY_PATH;
 
 echo "Configuring..."
 #see next call below for otb applications
@@ -62,6 +66,74 @@ $OUT_DIR/bin/mapla "\$@"
 EOF
 
 chmod +x "$OUT_DIR/mapla.sh"
+
+
+WITH_PYTHON=@WITH_PYTHON@
+
+if [ "$WITH_PYTHON" = true ] ; then
+
+if [ ! -f "$OTB_PYTHON_EXE" ] ; then
+    OTB_PYTHON_EXE=$(which python)
+fi
+
+python_INSTALLED_SONAME=@python_INSTALLED_SONAME@
+
+python_major_version=$($OTB_PYTHON_EXE -c "import sys;print(sys.version_info[0])")
+python_minor_version=$($OTB_PYTHON_EXE -c "import sys;print(sys.version_info[1])")
+python_patch_version=$($OTB_PYTHON_EXE -c "import sys;print(sys.version_info[2])")
+python_version="$python_major_version.$python_minor_version.$python_patch_version"
+
+python_check_failed() {
+    printf %s\\n "*****Error occurred during installation******"
+    printf %s\\n "OTB python bindings requires python2.6 or python2.7 but current detected python version is $python_version"
+    printf %s\\n "If you have python2.6 or Python2.7 installed in your system "
+    printf %s\\n "You should set OTB_PYTHON_EXE and re-run this installation script."
+    printf %s\\n "eg: OTB_PYTHON_EXE=/path/to/python2.7 ./OTB-X.Y-Linux64.run"
+    exit 1;
+}
+if [ "$python_major_version" -gt 2 ]; then
+python_check_failed
+fi
+
+if [ "$python_minor_version" -lt 5 ]; then
+python_check_failed
+fi
+
+python_INSTSONAME=$($OTB_PYTHON_EXE -c "import sys; from distutils import sysconfig; print (sysconfig.get_config_var('INSTSONAME'));")
+
+python_lib_dirs="$LD_LIBRARY_PATH_COPY /usr/lib /usr/lib64 /usr/lib/x86_64-linux-gnu"
+found_python_lib="0"
+python_lib_file_path=""
+for list_of_dir in $python_lib_dirs
+do
+    if [ -f "$list_of_dir/$python_INSTSONAME" ]; then
+        python_lib_file_path="$list_of_dir/$python_INSTSONAME"
+        found_python_lib="1"
+        break
+    fi
+done
+
+if [ "$found_python_lib" -eq "1" ]; then
+    printf %s\\n "OTB python bindings will be configured for $OTB_PYTHON_EXE ( version: $python_version )"
+    printf %s\\n "Found python library: $python_lib_file_path"
+    ln -sf "$python_lib_file_path" "$OUT_DIR/lib/$python_INSTALLED_SONAME"
+    "$PATCH_ELF_EXE" "--set-rpath" "$OUT_DIR/lib" "$OUT_DIR/lib/python/_otbApplication.so"
+    printf %s\\n "To use OTB python bindings:"
+    printf %s\\n "'export PYTHONPATH=$OUT_DIR/lib/python'"
+    printf %s\\n "To test OTB python bindings:"
+    printf %s\\n "$OTB_PYTHON_EXE -c 'import otbApplication'"
+else
+    printf %s\\n "*****Error occurred during installation******"
+    printf %s\\n "Python interpreter detected is : $OTB_PYTHON_EXE ( version: $python_version )"
+    printf %s\\n "$python_INSTSONAME cannot be found in any of search directories."
+    printf %s\\n "We had searched following directories $python_lib_dirs"
+    printf %s\\n "If you don't have python-dev package installed, install it and make a symlink"
+    printf %s\\n "If you don't have python headers and so installed on a custom location, then make a symlink"
+    printf %s\\n "eg: ln -s /usr/lib/x86_64-linux-gnu/$python_INSTSONAME $OUT_DIR/lib/$python_INSTALLED_SONAME"
+fi
+
+fi;
+
 
 cat > "$OUT_DIR/otbenv.profile" << EOF
 #!/bin/sh
@@ -155,7 +227,6 @@ export PATH
 
 EOF
 
-
 chmod +x "$OUT_DIR/xdkenv.profile"
 
 fi
@@ -170,71 +241,7 @@ Translations=$OUT_DIR/lib/qt4/translations
 Plugins=$OUT_DIR/lib/qt4/plugins
 EOF
 
-WITH_PYTHON=@WITH_PYTHON@
 
-if [ "$WITH_PYTHON" = true ] ; then
-
-if [ ! -f "$OTB_PYTHON_EXE" ] ; then
-    OTB_PYTHON_EXE=$(which python)
-fi
-
-python_INSTALLED_SONAME=@python_INSTALLED_SONAME@
-
-python_major_version=$($OTB_PYTHON_EXE -c "import sys;print(sys.version_info[0])")
-python_minor_version=$($OTB_PYTHON_EXE -c "import sys;print(sys.version_info[1])")
-python_patch_version=$($OTB_PYTHON_EXE -c "import sys;print(sys.version_info[2])")
-python_version="$python_major_version.$python_minor_version.$python_patch_version"
-
-python_check_failed() {
-    printf %s\\n "*****Error occurred during installation******"
-    printf %s\\n "OTB python bindings requires python2.6 or python2.7 but current detected python version is $python_version"
-    printf %s\\n "If you have python2.6 or Python2.7 installed in your system "
-    printf %s\\n "You should set OTB_PYTHON_EXE and re-run this installation script."
-    printf %s\\n "eg: OTB_PYTHON_EXE=/path/to/python2.7 ./OTB-X.Y-Linux64.run"
-    exit 1;
-}
-if [ "$python_major_version" -gt 2 ]; then
-python_check_failed
-fi
-
-if [ "$python_minor_version" -lt 5 ]; then
-python_check_failed
-fi
-
-python_INSTSONAME=$($OTB_PYTHON_EXE -c "import sys; from distutils import sysconfig; print (sysconfig.get_config_var('INSTSONAME'));")
-
-python_lib_dirs="/usr/lib /usr/lib64 /usr/lib/x86_64-linux-gnu"
-found_python_lib="0"
-python_lib_file_path=""
-for list_of_dir in $python_lib_dirs
-do
-    if [ -f "$list_of_dir/$python_INSTSONAME" ]; then
-        python_lib_file_path="$list_of_dir/$python_INSTSONAME"
-        found_python_lib="1"
-        break
-    fi
-done
-
-if [ "$found_python_lib" -eq "1" ]; then
-    printf %s\\n "OTB python bindings will be configured for $OTB_PYTHON_EXE ( version: $python_version )"
-    printf %s\\n "Found python library: $python_lib_file_path"
-    ln -sf "$python_lib_file_path" "$OUT_DIR/lib/$python_INSTALLED_SONAME"
-    "$PATCH_ELF_EXE" "--set-rpath" "$OUT_DIR/lib" "$OUT_DIR/lib/python/_otbApplication.so"
-    printf %s\\n "To use OTB python bindings:"
-    printf %s\\n "'export PYTHONPATH=$OUT_DIR/lib/python'"
-    printf %s\\n "To test OTB python bindings:"
-    printf %s\\n "$OTB_PYTHON_EXE -c 'import otbApplication'"
-else
-    printf %s\\n "*****Error occurred during installation******"
-    printf %s\\n "Python interpreter detected is : $OTB_PYTHON_EXE ( version: $python_version )"
-    printf %s\\n "$python_INSTSONAME cannot be found in any of search directories."
-    printf %s\\n "We had searched following directories $python_lib_dirs"
-    printf %s\\n "If you don't have python-dev package installed, install it and make a symlink"
-    printf %s\\n "If you don't have python headers and so installed on a custom location, then make a symlink"
-    printf %s\\n "eg: ln -s /usr/lib/x86_64-linux-gnu/$python_INSTSONAME $OUT_DIR/lib/$python_INSTALLED_SONAME"
-fi
-
-fi; 
 
 # PKG_OTB_VERSION_STRING=@PKG_OTB_VERSION_STRING@
 sed -i "s,|release|,@PKG_OTB_VERSION_STRING@,g" "$OUT_DIR/README"
