PKG: try to improve deployment scripts

diff --git a/Packaging/Files/linux_pkgsetup.in b/Packaging/Files/linux_pkgsetup.in
--- a/Packaging/Files/linux_pkgsetup.in
+++ b/Packaging/Files/linux_pkgsetup.in
@@ -20,6 +20,17 @@
 #
 set -e
 
+# verify basic tools are here
+which 2>/dev/null || ret=$?
+if [ ! $ret -eq 0 ] ; then echo "ERROR: Missing tool 'which'"; exit 1 ; fi
+for tool in dirname find file grep cut sed chmod cat readlink ; do
+  if [ -z "$(which $tool)" ] ; then
+    echo "ERROR: Missing tool '${tool}'"
+    echo "Please install it and make sure it can be found from PATH"
+    exit 1;
+  fi
+done
+
 DIRNAME_0=$(dirname "$0")
 cd  "$DIRNAME_0"
 
@@ -32,20 +43,16 @@ PATCH_ELF_EXE="$OUT_DIR/patchelf"
 
 #do not move below block. it must be before "unset LD_LIBRARY_PATH" code
 #check if we have any python bindings
-OTB_PYTHON_LIB_PATH=
 if [ -f "$OUT_DIR/lib/python/_otbApplication.so" ] ; then
-    sed -i "s,OUT_DIR,$OUT_DIR,g" "$OUT_DIR/setup_python.sh"
     chmod +x $OUT_DIR/setup_python.sh
-    . ./setup_python.sh
-    OTB_PYTHON_LIB_PATH=$OUT_DIR/lib/python
+    ./setup_python.sh || setup_python_ret=$?
 fi
 
 # No no interference with LD_LIBRARY_PATH
 unset LD_LIBRARY_PATH
 
-#RK: We cannot avoid -maxdepth 1 option in find command below because,
-# there are files in $OUT_DIR/lib/gtk which we CANNOT add new rpath
-BINARY_FILES=$(find $OTB_PYTHON_LIB_PATH $OUT_DIR/lib $OUT_DIR/bin $OUT_DIR/lib/otb/applications -maxdepth 1 -type f -exec file {} \; | grep -i elf|cut -f1 -d':')
+# we remove files in $OUT_DIR/lib/gtk which we CANNOT add new rpath
+BINARY_FILES=$(find $OUT_DIR/lib $OUT_DIR/bin -type f -exec file {} \; | grep -v '/lib/gtk/' | grep -i elf|cut -f1 -d':')
 # run patchelf
 for bin_file in $BINARY_FILES; do
     #echo "adding rpath to $bin_file"
diff --git a/Packaging/Files/macx_pkgsetup.in b/Packaging/Files/macx_pkgsetup.in
--- a/Packaging/Files/macx_pkgsetup.in
+++ b/Packaging/Files/macx_pkgsetup.in
@@ -20,6 +20,17 @@
 #
 set -e
 
+# verify basic tools are here (install_name_tool is specific macOS)
+which 2>/dev/null || ret=$?
+if [ ! $ret -eq 0 ] ; then echo "ERROR: Missing tool 'which'"; exit 1 ; fi
+for tool in dirname find file grep cut sed chmod cat readlink install_name_tool ; do
+  if [ -z "$(which $tool)" ] ; then
+    echo "ERROR: Missing tool '${tool}'"
+    echo "Please install it and make sure it can be found from PATH"
+    exit 1;
+  fi
+done
+
 DIRNAME_0=$(dirname "$0")
 cd  "$DIRNAME_0" || exit 1
 
@@ -29,16 +40,9 @@ cd  "$DIRNAME_0" || exit 1
 OUT_DIR=$(pwd)
 
 #do not move below 3 lines. it must be before "unset LD_LIBRARY_PATH" code
-sed -i "" "s,OUT_DIR,$OUT_DIR,g" "$OUT_DIR/setup_python.sh"
-chmod +x $OUT_DIR/setup_python.sh
-./setup_python.sh
-
-# find install_name_tool
-INSTALL_NAME_TOOL=$(which install_name_tool)
-if [ -z "$INSTALL_NAME_TOOL" ]; then
-    echo "install_name_tool does not exists.."
-    echo "please install install_name_tool and make sure it can be found from PATH"
-    exit 1;
+if [ -f "$OUT_DIR/lib/python/_otbApplication.so" ] ; then
+  chmod +x $OUT_DIR/setup_python.sh
+  ./setup_python.sh || setup_python_ret=$?
 fi
 
 # no interference with DYLD_LIBRARY_PATH and DYLD_FALLBACK_LIBRARY_PATH
